### PR TITLE
Datamining blog

### PR DESCRIPTION
**Pull request by pavolloffay**
Introduction to Datamining module

Please don't merge yet.

### CODE REVIEW

**Comment by jkremser** [comment]
it looks good, here is some feedback http://pastebin.com/GYuB2v7t

**Comment by pavolloffay** [comment]
Thanks Jirka, feedback was merged :+1:

**Comment by pavolloffay** [comment]
@lucasponce could you please review too.

**Comment by lucasponce** [comment]
Hi @pavolloffay , the post look ok to me. Also, it makes me thing that we need to extend some feature that currently is working inside of alerts in a way that prediction module can use it. I imagine that the prediction module would need to be notified when a threshold (or in general a condition) has changed. To recalculate the algorithm of the predictions. Today that is supported internally, but perhaps we need to extend the API to let other modules to be notified as well. I'll put that on our roadmap too.

Thanks for the post.

**Pull request merged**
