### PR TITLE
Migrating the auto-pr-deployment to another server.

### PR DESCRIPTION
**Pull request by jkremser**
To make this working also the env property of the travis build has to be set correctly (`DEPLOY_PR_HOST`). That would be the last step.

The machine is 1GB ram, 1 core and 10gigs of disk space and it handles the load well. It's free for a week then I will be paying for it. It's $3 per month.

### CODE REVIEW

**Comment by abonas** [comment]
@Jiri-Kremser I think that would be a problem moving to an infra that you would be paying for, I think it's not the right direction. cc @pilhuhn @theute

**Comment by jkremser** [comment]
> I think that would be a problem moving to an infra that you would be paying for, I think it's not the right direction. cc [@pilhuhn](https://github.com/pilhuhn) [@theute](https://github.com/theute)

@jpkrohling offered his help here, but afaik he is also paying for his machines

**Comment by theute** [comment]
What's needed on the hosting machine ?

**Comment by jkremser** [comment]
> What's needed on the hosting machine ?

not much. It needs to have a public IP, ports 10000-11000 open and that's it. Package-wise it's only: git, at, maven, curl, ruby, nc

**Pull request merged**
