### PR TITLE
Blog post on QR Code support for Android Client

### PR DESCRIPTION
**Pull request by openwarrior**

### CODE REVIEW

**Comment by jkremser** [comment]
This is good! If the `hostname:port` was also encoded in the QR code, there would be no need to even enter it.

**Comment by pilhuhn** [comment]
@Jiri-Kremser Yes. We should ask @jpkrohling if that is doable.

@anuj1708 It would be good, if that is possible, if the token generated from the Android app would put add a comment saying so.

**Comment by pilhuhn** [comment]
Great stuff @anuj1708 :+1:

**Comment by openwarrior** [comment]
@pilhuhn and @Jiri-Kremser  Thank you :)

**Pull request merged**
