### PR TITLE
Blog about inventory 0.15.0.Final release.

### PR DESCRIPTION
**Pull request by metlos**

### CODE REVIEW

**Comment by metlos** [comment]
@pilhuhn, could you please take a look at this? Let's hope that by merging this PR, the rest docs will get updated, too.

**Comment by jkremser** [comment]
> Let's hope that by merging this PR, the rest docs will get updated, too.

It would have been updated if it had been in the `swagger` branch, but it's not https://github.com/hawkular/hawkular.github.io/tree/swagger last change is 2 months old. So there is still some issue.

**Comment by pilhuhn** [comment]
On 27 Apr 2016, at 14:54, Jirka Kremser wrote:

> > Let's hope that by merging this PR, the rest docs will get updated, 
> > too.
> 
> It would have been updated if it had been in the `swagger` branch, but 
> it's not https://github.com/hawkular/hawkular.github.io/tree/swagger 
> last change is 2 months old. So there is still some issue.

I thought @lucasponce recently had done an update of the Alerts
rest-api (?)

**Comment by lucasponce** [comment]
Yes. It was this commit https://github.com/hawkular/hawkular.github.io/commit/8cb18b20dd01209d35d577246f2ca59598f45451 and it seems to be updated on the Hawkular.org site.

**Comment by metlos** [comment]
Just an FYI, we're solving some issues in inventory that is apparently not triggering these updates...

**Comment by jkremser** [comment]
Right, I believe I have the fix in here https://github.com/hawkular/hawkular-inventory/pull/255 However, this isn't blocking this PR. The docs are published to the hawkular.org whenever the hawkular.github.io repo is built. But if needed we can run the build manually, by re-spinning the last build in travis.

EDIT: oh, the blog post mentions the improved REST docs, so let's wait for the fix..

**Comment by jkremser** [comment]
docs got updated, We are happy, Vincent :)
pulp fiction

**Pull request merged**
