### PR TITLE
update secure comm docs with security-realm changes

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by pilhuhn** [comment]
@jmazzitelli Can you indicate from which agent version on this is valid?
Perhaps leave the old version and the new one and list valid versions?
We can then in a later PR remove the old one when the new agent is sufficiently in use?

**Comment by jmazzitelli** [comment]
> @jmazzitelli Can you indicate from which agent version on this is valid?

It should be valid for all versions. The "old" docs don't work with the new master build and upcoming release. The "new" docs (this PR) will work with the new master build and upcoming release as well as all previous released versions.

**Comment by pilhuhn** [comment]
So we should hold this until a new release is made

**Comment by jmazzitelli** [comment]
> So we should hold this until a new release is made

We do not need to hold this. These instructions work with what we have released already.

The change is just saying you only need to define a "truststore" not a "keystore".  For this security-realm you do not really need to specify this as a "keystore" (with a key alias and key password) because you only need this as a "truststore". So the change in config is merely that. You still are getting a certificate in your security realm keystore, but you don't need it defined with a key alias/password (since the agent isn't using this security realm for incoming connections).

**Comment by jkremser** [comment]
btw. I recall a presentation and demo given by Josef Casek from RedHat about using the lestsencrypt certs with wildfly. He had some automated method for it. Just in case you are interested:

slides:
https://rawgit.com/kwart/presentations/master/2016-11-JBUGcz-wildfly-10.1/index.html#23

demo code:
https://github.com/kwart/presentations/tree/master/2016-11-JBUGcz-wildfly-10.1/demo

here is the script that does the magic using the `jboss cli`, `openssl` and `letsencrypt` client

https://github.com/kwart/presentations/blob/master/2016-11-JBUGcz-wildfly-10.1/demo/scripts/letsencrypt/lets-encrypt-wildfly.sh

**Pull request merged**
