### PR TITLE
Initial Alerting Documentation for Metrics

### PR DESCRIPTION
**Pull request by jshaughn**
- related to work for hwkmetrics-566

### CODE REVIEW

**Comment by lucasponce** [comment]
As commented, the feature is great, but I am concerned about the doc.
I think this doc could be structured in other way, perhaps a chapter into Alerting guide to describe high level concepts, and the details of this alerter.
In special, if an end user wants to create a trigger, it is not clear how to do it with this doc.
So my proposal is to move this to alerter, and perhaps to cross-linking, with the references.
In metrics doc, it is good to maintain the details about the functions available, types of metrics, etc.

I like the doc as a technical/contributor user, but I think that as an end user it might lead with some confusion (when to use one trigger or another?, how?).

This is not only for this alerter, the EventsAlerter also have some concerns and at some point we need to arrange it, but I guess we should use this as a trigger to review the structure of the doc.

**Comment by jshaughn** [comment]
@lucasponce I've filled out the document a bit more.  Although I don't think it really addresses your concerns, I do think all of the information I've added so far is appropriate for an 'Alerting' section in the Metrics user guide.  This Alerter is specific to Metrics and so the content needs to be here, not in the Halerting documents.  It doesn't mean that some of the content isn't general, but most is specific to this Alerter.  I do have links to the Alerting guides/examples up front, with the recommendation that the reader understand alerting in general before proceeding.  So as for how to create a trigger and so forth, I think if that information is lacking it means we need to improve the Halerting docs.

Always it helps to have example/tutorial/demo style docs as well.  I think that could be done in addition to this guide, so I think what is here should be merged as-is, depending on timing of the feature release.  

@stefannegrea Should this wait for the feature to be released or do you guys use something like 'Since <version>', if so we could just set this section to something like 'Since 0.24'.

**Comment by lucasponce** [comment]
I think that documentation requires a re-organization.
Because in the way it is today, it has gaps that might lead in a bad usage of the alerting component.
But this is a bigger topic and perhaps is out (but related) scope of this PR.

The last changes look much better rather then preliminary ones.

LGTM

**Comment by jshaughn** [comment]
@stefannegrea The updated alerter has been merged into master, so this is free to be merged when you see fit.

**Comment by jshaughn** [comment]
@stefannegrea wondering if you missed this merge or are holding for some reason?

**Pull request merged**
