### PR TITLE
Add reference to jaeger and blog post

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@theute @pilhuhn @pavolloffay @jpkrohling  Added note and also updated the image to more recent style.

**Comment by theute** [comment]
I would move the paragraph before the "Who Should Be Interested?" title,
and use WARNING rather than NOTE.
Also mention that the focus on Hawkular APM project has been de-emphasized
in favor of Jaeger

**Comment by objectiser** [comment]
@theute If moved before the "Who Should be interested", then we need to add another title, otherwise it places it in the left hand menu area. Any thoughts on a title?

**Comment by jpkrohling** [comment]
Looks like the image is broken when viewed via GitHub? Otherwise, LGTM

**Review by pavolloffay — APPROVED** [review]

**Comment by theute** [comment]
LGTM

**Comment by objectiser** [comment]
Thanks all!

**Pull request merged**
