### PR TITLE
Blog update tags, datamining, tracing, opentracing

### PR DESCRIPTION
**Pull request by pavolloffay**
@pilhuhn could you please review?

cc @jpkrohling @objectiser I have added `tracing` and `opentracing` to my blogs.

### CODE REVIEW

**Comment by objectiser** [comment]
LGTM :+1:

**Comment by pilhuhn** [comment]
@pavolloffay  When you change "data mining" to "datamining" which is fine, can you also change the one document that is then left : http://www.hawkular.org/tags/data%20mining.html

**Comment by pilhuhn** [comment]
I changed the document nothing more to do.
Thanks @pavolloffay

**Comment by pavolloffay** [comment]
@pilhuhn thanks! It's great that it works for docs too :+1:

**Pull request merged**
