### PR TITLE
Announce 1.0.0.Alpha4

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@mtho11 Could you please review, esp. the UI part? https://github.com/hawkular/hawkular.github.io/commit/4a29b8bdf4941beea16537e97cf5d58e599509ce#diff-540681a06e3f535a87c9c6a94063e500R10

@theute are there more items to add in "what's next" section? https://github.com/hawkular/hawkular.github.io/commit/4a29b8bdf4941beea16537e97cf5d58e599509ce#diff-540681a06e3f535a87c9c6a94063e500R86

Otherwise OK?

**Comment by ppalaga** [comment]
@jpkrohling the RH access topic is fully missing in the Announcement. Would you mind writing a couple of lines?

**Comment by ppalaga** [comment]
c7be089 added `src/main/jbake/assets/properties.json` and `src/main/jbake/content/blog/2015/08/27/hawkular-1.0.0.Alpha4-released.adoc` as suggested by @theute

**Comment by ppalaga** [comment]
b44417d added the Access Portal integration text https://github.com/hawkular/hawkular.github.io/commit/b44417d0ed771939cf05094b44b5bc3111c75e7e#diff-540681a06e3f535a87c9c6a94063e500R49

**Comment by theute** [comment]
Could you remove: "As a tech preview, an " (Tech preview has a particular meaning for Red Hat support, I would not want to confuse people more)

**Comment by theute** [comment]
Otherwise I think it's good to go (will need to check once pushed)

**Comment by ppalaga** [comment]
4bc4d57 removed "As a tech preview" and fixed the youtube video ID.

**Pull request merged**
