### PR TITLE
Update the camel-opentracing blog as GlobalTracer is not longer requi…

### PR DESCRIPTION
**Pull request by objectiser**
…red - as this area of OpenTracing is changing in the near future

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay @jpkrohling Could you review please?

The camel-opentracing component has been updated to remove dependence on GlobalTracer as this functionality is moving into the core opentracing-java repo - but is not yet merged/stable - and the camel component doesn't really need to use it anyway. So have updated this blog to avoid using it in the zipkin demo.

Also update the brave-opentracing version to include the fix from @pavolloffay, so the service names now show up in the UI :)

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
LGTM!

**Comment by objectiser** [comment]
@jpkrohling Thanks

@pilhuhn / @theute Ok to merge?

**Comment by objectiser** [comment]
@pilhuhn Thanks!

**Pull request merged**
