### PR TITLE
Directory root name change

### PR DESCRIPTION
**Pull request by theute**
I had some merge/rebase issues (or git lack of knowledge) and ended up with a forced push.

It may be safer to cherry-pick my 2 real commits...

### CODE REVIEW

**Comment by theute** [comment]
That's 3 commits now

**Comment by theute** [comment]
By the way, I didn't know how to test the Travis hook so it was not tested

**Comment by jkremser** [comment]
Thomas, would you mind if I apply your changes from this pr in https://github.com/hawkular/hawkular.github.io/pull/51 and close it unmerged? mvn filtering wasn't the right thing to do

**Comment by jkremser** [comment]
As per talking on IRC, I am closing this PR on behalf of #51

**Pull request closed without merging**
