### PR TITLE
Some corrections for Hawkular Metrics user guide

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Comment by jmartisk** [comment]
Btw, anyone knows where the source of this page is? http://www.hawkular.org/docs/rest/rest-metrics.html I can't find it anywhere. The resulting WAR doesn't contain this, but somehow it's still deployed on the live site; there's a broken link to it from the user guide so I updated that link to point to the deployed instance, but it's probably not a good permanent solution

**Comment by lucasponce** [comment]
@jmartisk there was a CI/CD pseudo-pipeline to trigger the API generation.
It is hold under the branch 
https://github.com/hawkular/hawkular.github.io/tree/swagger

**Comment by jmartisk** [comment]
@lucasponce ok thanks, in that case the link is just incorrect and should start working after this PR

**Comment by lucasponce** [comment]
Hey @jmartisk I didn't see this PR. For some reason it was filtered out of my list.
Feel free also to merge it.

**Comment by jmartisk** [comment]
@lucasponce  Haha I completely forgot about it now too, so thanks for reminding me about its existence :smiley:  I don't have the permission to merge though. Perhaps @pilhuhn can? I can see him in the Hawkular organization :)

**Pull request merged**
